#include<iostream>
using namespace std;
/*what is stackover flow and stack underflow program**************************
************************************************************************
**********************************************************************
************************************************************************
**********************************************************************
************************************************************************
**********************************************************************
************************************************************************
**********************************************************************/
class myExcp: public exception
{   
    public:
    string x="error";
};
int main()
{
int a=1,b=3,z;
try{
    if(b>1)
throw myExcp(); //use defult constructor to throw object

z=a+b;
}

catch(myExcp a)
{
    cout<<a.x<<endl;

}
return 0;
}